/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "comparator_bigger.v:1" *)
module comparator_bigger(a, b, gt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "comparator_bigger.v:2" *)
  input [7:0] a;
  (* src = "comparator_bigger.v:3" *)
  input [7:0] b;
  (* src = "comparator_bigger.v:4" *)
  output gt;
  assign gt = 16'h0733 >> { _04_, _10_, _00_, _06_ };
  assign _00_ = 8'hb0 >> { _01_, _02_, _03_ };
  assign _01_ = 16'h8eaf >> { a[6], a[7], b[6], b[7] };
  assign _02_ = 16'h9009 >> { a[7], b[7], a[6], b[6] };
  assign _03_ = 16'h8eaf >> { a[4], a[5], b[4], b[5] };
  assign _04_ = 4'h8 >> { _05_, _02_ };
  assign _05_ = 16'h9009 >> { a[5], b[5], a[4], b[4] };
  assign _06_ = 8'hb0 >> { _07_, _08_, _09_ };
  assign _07_ = 16'h8eaf >> { a[2], a[3], b[2], b[3] };
  assign _08_ = 16'h9009 >> { a[3], b[3], a[2], b[2] };
  assign _09_ = 16'h2b22 >> { b[0], a[0], a[1], b[1] };
  assign _10_ = 4'h8 >> { _11_, _08_ };
  assign _11_ = 16'h9009 >> { a[1], b[1], a[0], b[0] };
endmodule
