/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "comparator_bigger.v:1" *)
module comparator_bigger(a, b, gt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "comparator_bigger.v:2" *)
  input [7:0] a;
  (* src = "comparator_bigger.v:3" *)
  input [7:0] b;
  (* src = "comparator_bigger.v:4" *)
  output gt;
  assign gt = 16'h0733 >> { _04_, _02_, _00_, _06_ };
  assign _00_ = 32'd1305414733 >> { b[6], a[6], a[7], b[7], _01_ };
  assign _01_ = 16'h7150 >> { a[4], a[5], b[4], b[5] };
  assign _02_ = 32'd1090519105 >> { a[1], b[1], a[0], b[0], _03_ };
  assign _03_ = 16'h6ff6 >> { a[3], b[3], a[2], b[2] };
  assign _04_ = 32'd1090519105 >> { a[5], b[5], a[4], b[4], _05_ };
  assign _05_ = 16'h6ff6 >> { a[7], b[7], a[6], b[6] };
  assign _06_ = 32'd1305414733 >> { b[2], a[2], a[3], b[3], _07_ };
  assign _07_ = 16'hd4dd >> { b[0], a[0], a[1], b[1] };
endmodule
