/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "comparator_bigger.v:1" *)
module comparator_bigger(a, b, gt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  (* src = "comparator_bigger.v:2" *)
  input [15:0] a;
  (* src = "comparator_bigger.v:3" *)
  input [15:0] b;
  (* src = "comparator_bigger.v:4" *)
  output gt;
  assign gt = 16'h0733 >> { _11_, _24_, _00_, _13_ };
  assign _00_ = 8'hb0 >> { _01_, _05_, _07_ };
  assign _01_ = 8'hb0 >> { _02_, _03_, _04_ };
  assign _02_ = 16'h8eaf >> { a[14], a[15], b[14], b[15] };
  assign _03_ = 16'h9009 >> { a[15], b[15], a[14], b[14] };
  assign _04_ = 16'h8eaf >> { a[12], a[13], b[12], b[13] };
  assign _05_ = 4'h8 >> { _06_, _03_ };
  assign _06_ = 16'h9009 >> { a[13], b[13], a[12], b[12] };
  assign _07_ = 8'hb0 >> { _08_, _09_, _10_ };
  assign _08_ = 16'h8eaf >> { a[10], a[11], b[10], b[11] };
  assign _09_ = 16'h9009 >> { a[11], b[11], a[10], b[10] };
  assign _10_ = 16'h8eaf >> { a[8], a[9], b[8], b[9] };
  assign _11_ = 8'h80 >> { _12_, _09_, _05_ };
  assign _12_ = 16'h9009 >> { a[9], b[9], a[8], b[8] };
  assign _13_ = 8'hb0 >> { _14_, _18_, _20_ };
  assign _14_ = 8'hb0 >> { _15_, _16_, _17_ };
  assign _15_ = 16'h8eaf >> { a[6], a[7], b[6], b[7] };
  assign _16_ = 16'h9009 >> { a[7], b[7], a[6], b[6] };
  assign _17_ = 16'h8eaf >> { a[4], a[5], b[4], b[5] };
  assign _18_ = 4'h8 >> { _19_, _16_ };
  assign _19_ = 16'h9009 >> { a[5], b[5], a[4], b[4] };
  assign _20_ = 8'hb0 >> { _21_, _22_, _23_ };
  assign _21_ = 16'h8eaf >> { a[2], a[3], b[2], b[3] };
  assign _22_ = 16'h9009 >> { a[3], b[3], a[2], b[2] };
  assign _23_ = 16'h2b22 >> { b[0], a[0], a[1], b[1] };
  assign _24_ = 8'h80 >> { _25_, _22_, _18_ };
  assign _25_ = 16'h9009 >> { a[1], b[1], a[0], b[0] };
endmodule
