/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "comparator_bigger.v:1" *)
module comparator_bigger(a, b, gt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "comparator_bigger.v:2" *)
  input [15:0] a;
  (* src = "comparator_bigger.v:3" *)
  input [15:0] b;
  (* src = "comparator_bigger.v:4" *)
  output gt;
  assign gt = 64'h0fff0b000fff0fff >> { _06_, _00_, _13_, _08_, _18_, _15_ };
  assign _00_ = 32'd244 >> { _01_, _02_, _05_, _04_, _03_ };
  assign _01_ = 16'h6ff6 >> { a[14], b[14], a[15], b[15] };
  assign _02_ = 16'h6ff6 >> { a[13], b[13], a[12], b[12] };
  assign _03_ = 16'h6ff6 >> { a[11], b[11], a[10], b[10] };
  assign _04_ = 16'h7150 >> { a[8], a[9], b[8], b[9] };
  assign _05_ = 16'h7150 >> { a[10], a[11], b[10], b[11] };
  assign _06_ = 32'd1305414733 >> { b[14], a[14], a[15], b[15], _07_ };
  assign _07_ = 16'h7150 >> { a[12], a[13], b[12], b[13] };
  assign _08_ = 16'h0001 >> { _12_, _11_, _10_, _09_ };
  assign _09_ = 16'h6ff6 >> { a[7], b[7], a[6], b[6] };
  assign _10_ = 16'h6ff6 >> { a[4], b[4], a[5], b[5] };
  assign _11_ = 16'h6ff6 >> { a[2], b[2], a[3], b[3] };
  assign _12_ = 16'h6ff6 >> { a[1], b[1], a[0], b[0] };
  assign _13_ = 16'h0001 >> { _14_, _03_, _02_, _01_ };
  assign _14_ = 16'h6ff6 >> { a[8], b[8], a[9], b[9] };
  assign _15_ = 32'd244 >> { _09_, _10_, _17_, _16_, _11_ };
  assign _16_ = 16'hd4dd >> { b[0], a[0], a[1], b[1] };
  assign _17_ = 16'h7150 >> { a[2], a[3], b[2], b[3] };
  assign _18_ = 32'd1305414733 >> { b[6], a[6], a[7], b[7], _19_ };
  assign _19_ = 16'h7150 >> { a[4], a[5], b[4], b[5] };
endmodule
