/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "comparator_bigger.v:1" *)
module comparator_bigger(a, b, gt);
  wire _0_;
  wire _1_;
  (* src = "comparator_bigger.v:2" *)
  input [3:0] a;
  (* src = "comparator_bigger.v:3" *)
  input [3:0] b;
  (* src = "comparator_bigger.v:4" *)
  output gt;
  assign gt = 64'haaaaaaaa2cefae2c >> { _1_, a[0], b[0], b[1], a[1], _0_ };
  assign _0_ = 16'h7150 >> { a[2], a[3], b[2], b[3] };
  assign _1_ = 16'h6ff6 >> { a[2], b[2], a[3], b[3] };
endmodule
