/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "comparator_bigger.v:1" *)
module comparator_bigger(a, b, gt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "comparator_bigger.v:2" *)
  input [3:0] a;
  (* src = "comparator_bigger.v:3" *)
  input [3:0] b;
  (* src = "comparator_bigger.v:4" *)
  output gt;
  assign gt = 8'h35 >> { _04_, _00_, _02_ };
  assign _00_ = 8'hac >> { a[0], _01_, _03_ };
  assign _01_ = 16'hdc0d >> { b[1], a[1], _02_, b[0] };
  assign _02_ = 16'h8eaf >> { a[2], a[3], b[2], b[3] };
  assign _03_ = 16'hca0c >> { b[1], a[1], b[0], _02_ };
  assign _04_ = 16'h9009 >> { a[2], b[2], a[3], b[3] };
endmodule
