/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "comparator_bigger.v:1" *)
module comparator_bigger(a, b, gt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  (* src = "comparator_bigger.v:2" *)
  input [31:0] a;
  (* src = "comparator_bigger.v:3" *)
  input [31:0] b;
  (* src = "comparator_bigger.v:4" *)
  output gt;
  assign gt = 32'd117444607 >> { _07_, _34_, _24_, _05_, _37_ };
  
  assign _07_ = 64'h0000df0f00000000 >> { _22_, _08_, _14_, _20_, _16_, _18_ };
  assign _08_ = 32'd244 >> { _13_, _12_, _11_, _10_, _09_ };
  assign _34_ = 16'h1000 >> { _20_, _18_, _36_, _35_ };
  assign _37_ = 64'hbb0b0000ff0fff0f >> { _25_, _01_, _27_, _38_, _30_, _03_ };
  assign _24_ = 16'h1000 >> { _30_, _25_, _33_, _32_ };
  
  assign _25_ = 16'h0001 >> { _29_, _28_, _27_, _26_ };
  assign _20_ = 16'h0001 >> { _21_, _13_, _12_, _09_ };
  assign _14_ = 32'd1305414733 >> { b[22], a[22], a[23], b[23], _15_ };
  assign _16_ = 32'd1305414733 >> { b[18], a[18], a[19], b[19], _17_ };
  assign _18_ = 32'd1090519105 >> { a[21], b[21], a[20], b[20], _19_ };
  assign _22_ = 32'd1305414733 >> { b[30], a[30], a[31], b[31], _23_ };
  assign _30_ = 32'd1090519105 >> { a[5], b[5], a[4], b[4], _31_ };
  assign _38_ = 64'h00000000bf233b02 >> { _26_, a[10], a[11], b[10], b[11], _00_ };
  assign _01_ = 32'd1305414733 >> { b[6], a[6], a[7], b[7], _02_ };
  assign _03_ = 32'd1305414733 >> { b[2], a[2], a[3], b[3], _04_ };
  assign _05_ = 32'd1305414733 >> { b[14], a[14], a[15], b[15], _06_ };
  
  assign _02_ = 16'h7150 >> { a[4], a[5], b[4], b[5] };
  assign _04_ = 16'hd4dd >> { b[0], a[0], a[1], b[1] };
  assign _00_ = 16'h7150 >> { a[8], a[9], b[8], b[9] };
  assign _35_ = 16'h6ff6 >> { a[19], b[19], a[18], b[18] };
  assign _36_ = 16'h6ff6 >> { a[16], b[16], a[17], b[17] };
  assign _31_ = 16'h6ff6 >> { a[7], b[7], a[6], b[6] };
  assign _32_ = 16'h6ff6 >> { a[2], b[2], a[3], b[3] };
  assign _33_ = 16'h6ff6 >> { b[0], a[0], a[1], b[1] };
  assign _09_ = 16'h6ff6 >> { a[27], b[27], a[26], b[26] };
  assign _10_ = 16'h7150 >> { a[24], a[25], b[24], b[25] };
  assign _11_ = 16'h7150 >> { a[26], a[27], b[26], b[27] };
  assign _12_ = 16'h6ff6 >> { a[31], b[31], a[30], b[30] };
  assign _13_ = 16'h6ff6 >> { a[28], b[28], a[29], b[29] };
  assign _17_ = 16'h7150 >> { a[16], a[17], b[16], b[17] };
  assign _06_ = 16'h7150 >> { a[12], a[13], b[12], b[13] };
  assign _26_ = 16'h6ff6 >> { a[15], b[15], a[14], b[14] };
  assign _27_ = 16'h6ff6 >> { a[13], b[13], a[12], b[12] };
  assign _28_ = 16'h6ff6 >> { a[11], b[11], a[10], b[10] };
  assign _29_ = 16'h6ff6 >> { a[9], b[9], a[8], b[8] };
  assign _23_ = 16'h7150 >> { a[28], a[29], b[28], b[29] };
  assign _15_ = 16'h7150 >> { a[20], a[21], b[20], b[21] };
  assign _21_ = 16'h6ff6 >> { a[25], b[25], a[24], b[24] };
  assign _19_ = 16'h6ff6 >> { a[23], b[23], a[22], b[22] };
endmodule
