/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "comparator_bigger.v:1" *)
module comparator_bigger(a, b, gt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "comparator_bigger.v:2" *)
  input [3:0] a;
  (* src = "comparator_bigger.v:3" *)
  input [3:0] b;
  (* src = "comparator_bigger.v:4" *)
  output gt;
  NOT _17_ (
    .A(b[0]),
    .Y(_00_)
  );
  NOT _18_ (
    .A(b[1]),
    .Y(_01_)
  );
  NOT _19_ (
    .A(b[2]),
    .Y(_02_)
  );
  NOT _20_ (
    .A(a[3]),
    .Y(_03_)
  );
  AND _21_ (
    .A(b[3]),
    .B(_03_),
    .Y(_04_)
  );
  AND _22_ (
    .A(_01_),
    .B(a[1]),
    .Y(_05_)
  );
  AND _23_ (
    .A(_00_),
    .B(a[0]),
    .Y(_06_)
  );
  OR _24_ (
    .A(_05_),
    .B(_06_),
    .Y(_07_)
  );
  OR _25_ (
    .A(_02_),
    .B(a[2]),
    .Y(_08_)
  );
  OR _26_ (
    .A(_01_),
    .B(a[1]),
    .Y(_09_)
  );
  AND _27_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  NAND _28_ (
    .A(_07_),
    .B(_10_),
    .Y(_11_)
  );
  OR _29_ (
    .A(b[3]),
    .B(_03_),
    .Y(_12_)
  );
  NAND _30_ (
    .A(_02_),
    .B(a[2]),
    .Y(_13_)
  );
  AND _31_ (
    .A(_12_),
    .B(_13_),
    .Y(_14_)
  );
  AND _32_ (
    .A(_11_),
    .B(_14_),
    .Y(_15_)
  );
  OR _33_ (
    .A(_04_),
    .B(_15_),
    .Y(_16_)
  );
  assign gt = _16_ ? (* full_case = 32'd1 *) (* src = "comparator_bigger.v:9" *) 1'h0 : 1'h1;
endmodule
